### PR TITLE
Add more `AFKPlusPlayer` broadcast methods

### PR DESCRIPTION
**Pull request by srnyx**
Need it for https://github.com/srnyx/AFKPlusDiscord when sending messages to Discord channel

### CODE REVIEW

**Comment by srnyx** [comment]
wait actually i think i might need something different, maybe just returning the config values (with vanish modification), cause there arent recipients or whatever for discord

**Comment by srnyx** [comment]
alright there we go, that should work

**Comment by Dart2112** [comment]
Only one issue I can see,
`recipients.addAll(Bukkit.getOnlinePlayers());` at https://github.com/LapisPlugins/AFKPlus/pull/64/commits/d162c55389a07939e0102c9f67cc265d3010bc97#diff-aa72dcfe46b65b042a4041634a21478f780174f6c24871423e6abfc55ae129d5R287
using that for otherPlayers means that self being set to false while otherPlayers is true won't work because the player is already included.

So maybe if self is false, remove the player from the list? Either that or go back to the for loop for adding other players.

Otherwise, this is a great addition that I will be happy to merge

**Comment by srnyx** [comment]
> Only one issue I can see, `recipients.addAll(Bukkit.getOnlinePlayers());` at [d162c55#diff-aa72dcfe46b65b042a4041634a21478f780174f6c24871423e6abfc55ae129d5R287](https://github.com/LapisPlugins/AFKPlus/commit/d162c55389a07939e0102c9f67cc265d3010bc97#diff-aa72dcfe46b65b042a4041634a21478f780174f6c24871423e6abfc55ae129d5R287) using that for otherPlayers means that self being set to false while otherPlayers is true won't work because the player is already included.
> 
> So maybe if self is false, remove the player from the list? Either that or go back to the for loop for adding other players.

ah yeah true. removing if set to false is probably better as it wouldnt be running the check for every single player
also noticed it doesnt need to be a list, so ill make a set instead

**Comment by Dart2112** [comment]
It's currently an ungodly hour of the morning in my timezone, when I get a chance in the next 24 hours I will bump the version and push an update to the Maven repo.

**Comment by Dart2112** [comment]
JavaDocs and the repo should now be updated with v3.4.2 which contains these changes

**Pull request merged**
